// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {service} from '../models';
import {intruder} from '../models';
import {models} from '../models';

export function AddActiveScanTarget(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>,arg6:string):Promise<void>;

export function AddDictionaryEntry(arg1:api.DictEntry):Promise<void>;

export function AddScanResult(arg1:api.ScanResult):Promise<number>;

export function AddVulnerability(arg1:api.Vulnerability):Promise<number>;

export function AddWebSocketMessage(arg1:api.WebSocketMessage):Promise<number>;

export function ClearEmbeddedScanFindings():Promise<void>;

export function ClearScanResults():Promise<void>;

export function ClearTraffic():Promise<void>;

export function ClearWebSocketMessages():Promise<void>;

export function Connect():Promise<void>;

export function ConnectRemoteMode(arg1:service.RemoteConfig):Promise<void>;

export function CreateActiveScan(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:Array<string>):Promise<void>;

export function CreateActiveScanConfig(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:Array<string>):Promise<Record<string, any>>;

export function CreateActiveScanTarget(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string):Promise<Record<string, any>>;

export function CreateIntruderAttack(arg1:intruder.AttackConfig):Promise<string>;

export function CreateScannerRule(arg1:api.Rule):Promise<void>;

export function DeleteScanResult(arg1:number):Promise<void>;

export function DeleteVulnerability(arg1:number):Promise<void>;

export function DetectIntruderPositions(arg1:string):Promise<Array<Record<string, number>>>;

export function DisableActiveScanPlugin(arg1:string,arg2:string):Promise<void>;

export function DisableEmbeddedScanRule(arg1:string):Promise<void>;

export function DisableScannerRule(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DropIntercepted(arg1:string):Promise<void>;

export function EnableActiveScanPlugin(arg1:string,arg2:string):Promise<void>;

export function EnableEmbeddedScanRule(arg1:string):Promise<void>;

export function EnableScannerRule(arg1:string):Promise<void>;

export function EstimateIntruderRequestCount(arg1:string,arg2:number,arg3:Array<number>):Promise<number>;

export function ExportDictionary(arg1:string):Promise<void>;

export function ExportScanResultToVuln(arg1:number):Promise<number>;

export function ForwardIntercepted(arg1:string):Promise<void>;

export function GenerateHTMLReport(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<Array<number>>;

export function GenerateJSONReport(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<api.ReportData>;

export function GenerateMarkdownReport(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<Array<number>>;

export function GenerateReport(arg1:api.ReportOptions):Promise<Array<number>>;

export function GetAPIEndpoint():Promise<string>;

export function GetActiveScanFindings(arg1:string):Promise<Array<Record<string, any>>>;

export function GetActiveScanPlugins(arg1:string):Promise<Array<Record<string, any>>>;

export function GetActiveScanProgress(arg1:string):Promise<Record<string, any>>;

export function GetActiveScanStatus(arg1:string):Promise<string>;

export function GetActiveScanTargets(arg1:string):Promise<Array<Record<string, any>>>;

export function GetAppConfig():Promise<service.AppConfig>;

export function GetBindAddressOptions():Promise<Array<Record<string, string>>>;

export function GetConfigPath():Promise<string>;

export function GetConnectionMode():Promise<string>;

export function GetDatabaseInfo():Promise<Record<string, any>>;

export function GetDefaultActiveScanPlugins():Promise<Array<Record<string, any>>>;

export function GetDictionaryEntries(arg1:string,arg2:string,arg3:number):Promise<Array<api.DictEntry>>;

export function GetEmbeddedScanFindings():Promise<Array<Record<string, any>>>;

export function GetEmbeddedScanRules():Promise<Array<Record<string, any>>>;

export function GetFingerprintHistory(arg1:number):Promise<Array<models.FingerprintResult>>;

export function GetFingerprintStats():Promise<Record<string, any>>;

export function GetIntruderAttackProgress(arg1:string):Promise<Record<string, any>>;

export function GetIntruderAttackResults(arg1:string):Promise<Array<Record<string, any>>>;

export function GetIntruderAttackTypes():Promise<Array<api.AttackTypeInfo>>;

export function GetLocalServiceOutput():Promise<Array<string>>;

export function GetMetrics():Promise<models.DashboardMetrics>;

export function GetNetworkInterfaces():Promise<Array<api.NetworkInterface>>;

export function GetProxyConfig():Promise<api.ProxyConfig>;

export function GetProxyStatus():Promise<models.ProxyStatus>;

export function GetScanResults(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<api.ScanResult>>;

export function GetScannerRule(arg1:string):Promise<api.Rule>;

export function GetScannerRules():Promise<Array<api.Rule>>;

export function GetTraffic(arg1:number):Promise<Array<models.TrafficItem>>;

export function GetTrafficPatterns():Promise<Record<string, any>>;

export function GetVulnStats():Promise<Record<string, number>>;

export function GetVulnerabilities(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<api.Vulnerability>>;

export function GetWebSocketMessages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<api.WebSocketMessage>>;

export function IdentifyFingerprint(arg1:string):Promise<models.FingerprintResult>;

export function ImportDictionary():Promise<number>;

export function InitDatabase(arg1:api.DatabaseConfig):Promise<api.InitResult>;

export function IsConnected():Promise<boolean>;

export function IsLocalServiceRunning():Promise<boolean>;

export function IsScannerEnabled():Promise<boolean>;

export function ListActiveScans():Promise<Array<string>>;

export function ListIntruderAttacks():Promise<Array<string>>;

export function ListReports():Promise<Array<Record<string, any>>>;

export function MarkScanResultFalsePositive(arg1:number,arg2:boolean):Promise<void>;

export function ModifyAndForwardRequest(arg1:string,arg2:Record<string, any>):Promise<service.ModifiedRequestResult>;

export function PauseActiveScan(arg1:string):Promise<void>;

export function PauseIntruderAttack(arg1:string):Promise<void>;

export function ReloadScannerRules():Promise<number>;

export function RemoveActiveScan(arg1:string):Promise<void>;

export function RemoveActiveScanTarget(arg1:string,arg2:string):Promise<void>;

export function RemoveIntruderAttack(arg1:string):Promise<void>;

export function ResetAppConfig():Promise<void>;

export function ResumeActiveScan(arg1:string):Promise<void>;

export function ResumeIntruderAttack(arg1:string):Promise<void>;

export function SaveAppConfig(arg1:service.AppConfig):Promise<void>;

export function SaveProxyConfig(arg1:api.ProxyConfig):Promise<Record<string, string>>;

export function SaveReportToFile(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<string>):Promise<string>;

export function ScanRequest(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string):Promise<Array<Record<string, any>>>;

export function ScanResponse(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string,arg5:number):Promise<Array<Record<string, any>>>;

export function ScanTrafficMessage(arg1:string,arg2:string,arg3:Record<string, string>,arg4:string,arg5:string,arg6:number):Promise<Array<Record<string, any>>>;

export function SelectDatabaseFolder():Promise<string>;

export function SendRequest(arg1:models.RepeaterRequest):Promise<models.RepeaterResponse>;

export function SetAPIEndpoint(arg1:string):Promise<void>;

export function SetDatabaseForAPIs():Promise<void>;

export function SetInterceptMode(arg1:boolean):Promise<void>;

export function SetPollingInterval(arg1:number):Promise<void>;

export function SetScannerEnabled(arg1:boolean):Promise<void>;

export function StartActiveScan(arg1:string):Promise<void>;

export function StartIntruderAttack(arg1:string):Promise<void>;

export function StartLocalMode(arg1:service.LocalConfig):Promise<void>;

export function StopActiveScan(arg1:string):Promise<void>;

export function StopIntruderAttack(arg1:string):Promise<void>;

export function StopLocalService():Promise<void>;

export function TestConnection(arg1:string):Promise<Record<string, any>>;

export function UpdateAppConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateVulnerabilityStatus(arg1:number,arg2:string):Promise<void>;
