// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActiveScanTarget(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddActiveScanTarget'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddDictionaryEntry(arg1) {
  return window['go']['main']['App']['AddDictionaryEntry'](arg1);
}

export function AddScanResult(arg1) {
  return window['go']['main']['App']['AddScanResult'](arg1);
}

export function AddVulnerability(arg1) {
  return window['go']['main']['App']['AddVulnerability'](arg1);
}

export function AddWebSocketMessage(arg1) {
  return window['go']['main']['App']['AddWebSocketMessage'](arg1);
}

export function ClearEmbeddedScanFindings() {
  return window['go']['main']['App']['ClearEmbeddedScanFindings']();
}

export function ClearScanResults() {
  return window['go']['main']['App']['ClearScanResults']();
}

export function ClearTraffic() {
  return window['go']['main']['App']['ClearTraffic']();
}

export function ClearWebSocketMessages() {
  return window['go']['main']['App']['ClearWebSocketMessages']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function ConnectRemoteMode(arg1) {
  return window['go']['main']['App']['ConnectRemoteMode'](arg1);
}

export function CreateActiveScan(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateActiveScan'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateActiveScanConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateActiveScanConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CreateActiveScanTarget(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateActiveScanTarget'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateIntruderAttack(arg1) {
  return window['go']['main']['App']['CreateIntruderAttack'](arg1);
}

export function CreateScannerRule(arg1) {
  return window['go']['main']['App']['CreateScannerRule'](arg1);
}

export function DeleteScanResult(arg1) {
  return window['go']['main']['App']['DeleteScanResult'](arg1);
}

export function DeleteVulnerability(arg1) {
  return window['go']['main']['App']['DeleteVulnerability'](arg1);
}

export function DetectIntruderPositions(arg1) {
  return window['go']['main']['App']['DetectIntruderPositions'](arg1);
}

export function DisableActiveScanPlugin(arg1, arg2) {
  return window['go']['main']['App']['DisableActiveScanPlugin'](arg1, arg2);
}

export function DisableEmbeddedScanRule(arg1) {
  return window['go']['main']['App']['DisableEmbeddedScanRule'](arg1);
}

export function DisableScannerRule(arg1) {
  return window['go']['main']['App']['DisableScannerRule'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DropIntercepted(arg1) {
  return window['go']['main']['App']['DropIntercepted'](arg1);
}

export function EnableActiveScanPlugin(arg1, arg2) {
  return window['go']['main']['App']['EnableActiveScanPlugin'](arg1, arg2);
}

export function EnableEmbeddedScanRule(arg1) {
  return window['go']['main']['App']['EnableEmbeddedScanRule'](arg1);
}

export function EnableScannerRule(arg1) {
  return window['go']['main']['App']['EnableScannerRule'](arg1);
}

export function EstimateIntruderRequestCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['EstimateIntruderRequestCount'](arg1, arg2, arg3);
}

export function ExportDictionary(arg1) {
  return window['go']['main']['App']['ExportDictionary'](arg1);
}

export function ExportScanResultToVuln(arg1) {
  return window['go']['main']['App']['ExportScanResultToVuln'](arg1);
}

export function ForwardIntercepted(arg1) {
  return window['go']['main']['App']['ForwardIntercepted'](arg1);
}

export function GenerateHTMLReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateHTMLReport'](arg1, arg2, arg3, arg4);
}

export function GenerateJSONReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateJSONReport'](arg1, arg2, arg3, arg4);
}

export function GenerateMarkdownReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateMarkdownReport'](arg1, arg2, arg3, arg4);
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function GetAPIEndpoint() {
  return window['go']['main']['App']['GetAPIEndpoint']();
}

export function GetActiveScanFindings(arg1) {
  return window['go']['main']['App']['GetActiveScanFindings'](arg1);
}

export function GetActiveScanPlugins(arg1) {
  return window['go']['main']['App']['GetActiveScanPlugins'](arg1);
}

export function GetActiveScanProgress(arg1) {
  return window['go']['main']['App']['GetActiveScanProgress'](arg1);
}

export function GetActiveScanStatus(arg1) {
  return window['go']['main']['App']['GetActiveScanStatus'](arg1);
}

export function GetActiveScanTargets(arg1) {
  return window['go']['main']['App']['GetActiveScanTargets'](arg1);
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetBindAddressOptions() {
  return window['go']['main']['App']['GetBindAddressOptions']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetConnectionMode() {
  return window['go']['main']['App']['GetConnectionMode']();
}

export function GetDatabaseInfo() {
  return window['go']['main']['App']['GetDatabaseInfo']();
}

export function GetDefaultActiveScanPlugins() {
  return window['go']['main']['App']['GetDefaultActiveScanPlugins']();
}

export function GetDictionaryEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDictionaryEntries'](arg1, arg2, arg3);
}

export function GetEmbeddedScanFindings() {
  return window['go']['main']['App']['GetEmbeddedScanFindings']();
}

export function GetEmbeddedScanRules() {
  return window['go']['main']['App']['GetEmbeddedScanRules']();
}

export function GetFingerprintHistory(arg1) {
  return window['go']['main']['App']['GetFingerprintHistory'](arg1);
}

export function GetFingerprintStats() {
  return window['go']['main']['App']['GetFingerprintStats']();
}

export function GetIntruderAttackProgress(arg1) {
  return window['go']['main']['App']['GetIntruderAttackProgress'](arg1);
}

export function GetIntruderAttackResults(arg1) {
  return window['go']['main']['App']['GetIntruderAttackResults'](arg1);
}

export function GetIntruderAttackTypes() {
  return window['go']['main']['App']['GetIntruderAttackTypes']();
}

export function GetLocalServiceOutput() {
  return window['go']['main']['App']['GetLocalServiceOutput']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetNetworkInterfaces() {
  return window['go']['main']['App']['GetNetworkInterfaces']();
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetScanResults(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetScanResults'](arg1, arg2, arg3, arg4);
}

export function GetScannerRule(arg1) {
  return window['go']['main']['App']['GetScannerRule'](arg1);
}

export function GetScannerRules() {
  return window['go']['main']['App']['GetScannerRules']();
}

export function GetTraffic(arg1) {
  return window['go']['main']['App']['GetTraffic'](arg1);
}

export function GetTrafficPatterns() {
  return window['go']['main']['App']['GetTrafficPatterns']();
}

export function GetVulnStats() {
  return window['go']['main']['App']['GetVulnStats']();
}

export function GetVulnerabilities(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetVulnerabilities'](arg1, arg2, arg3, arg4);
}

export function GetWebSocketMessages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetWebSocketMessages'](arg1, arg2, arg3, arg4);
}

export function IdentifyFingerprint(arg1) {
  return window['go']['main']['App']['IdentifyFingerprint'](arg1);
}

export function ImportDictionary() {
  return window['go']['main']['App']['ImportDictionary']();
}

export function InitDatabase(arg1) {
  return window['go']['main']['App']['InitDatabase'](arg1);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsLocalServiceRunning() {
  return window['go']['main']['App']['IsLocalServiceRunning']();
}

export function IsScannerEnabled() {
  return window['go']['main']['App']['IsScannerEnabled']();
}

export function ListActiveScans() {
  return window['go']['main']['App']['ListActiveScans']();
}

export function ListIntruderAttacks() {
  return window['go']['main']['App']['ListIntruderAttacks']();
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function MarkScanResultFalsePositive(arg1, arg2) {
  return window['go']['main']['App']['MarkScanResultFalsePositive'](arg1, arg2);
}

export function ModifyAndForwardRequest(arg1, arg2) {
  return window['go']['main']['App']['ModifyAndForwardRequest'](arg1, arg2);
}

export function PauseActiveScan(arg1) {
  return window['go']['main']['App']['PauseActiveScan'](arg1);
}

export function PauseIntruderAttack(arg1) {
  return window['go']['main']['App']['PauseIntruderAttack'](arg1);
}

export function ReloadScannerRules() {
  return window['go']['main']['App']['ReloadScannerRules']();
}

export function RemoveActiveScan(arg1) {
  return window['go']['main']['App']['RemoveActiveScan'](arg1);
}

export function RemoveActiveScanTarget(arg1, arg2) {
  return window['go']['main']['App']['RemoveActiveScanTarget'](arg1, arg2);
}

export function RemoveIntruderAttack(arg1) {
  return window['go']['main']['App']['RemoveIntruderAttack'](arg1);
}

export function ResetAppConfig() {
  return window['go']['main']['App']['ResetAppConfig']();
}

export function ResumeActiveScan(arg1) {
  return window['go']['main']['App']['ResumeActiveScan'](arg1);
}

export function ResumeIntruderAttack(arg1) {
  return window['go']['main']['App']['ResumeIntruderAttack'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['main']['App']['SaveAppConfig'](arg1);
}

export function SaveProxyConfig(arg1) {
  return window['go']['main']['App']['SaveProxyConfig'](arg1);
}

export function SaveReportToFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveReportToFile'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanRequest'](arg1, arg2, arg3, arg4);
}

export function ScanResponse(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ScanResponse'](arg1, arg2, arg3, arg4, arg5);
}

export function ScanTrafficMessage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ScanTrafficMessage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SelectDatabaseFolder() {
  return window['go']['main']['App']['SelectDatabaseFolder']();
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetAPIEndpoint(arg1) {
  return window['go']['main']['App']['SetAPIEndpoint'](arg1);
}

export function SetDatabaseForAPIs() {
  return window['go']['main']['App']['SetDatabaseForAPIs']();
}

export function SetInterceptMode(arg1) {
  return window['go']['main']['App']['SetInterceptMode'](arg1);
}

export function SetPollingInterval(arg1) {
  return window['go']['main']['App']['SetPollingInterval'](arg1);
}

export function SetScannerEnabled(arg1) {
  return window['go']['main']['App']['SetScannerEnabled'](arg1);
}

export function StartActiveScan(arg1) {
  return window['go']['main']['App']['StartActiveScan'](arg1);
}

export function StartIntruderAttack(arg1) {
  return window['go']['main']['App']['StartIntruderAttack'](arg1);
}

export function StartLocalMode(arg1) {
  return window['go']['main']['App']['StartLocalMode'](arg1);
}

export function StopActiveScan(arg1) {
  return window['go']['main']['App']['StopActiveScan'](arg1);
}

export function StopIntruderAttack(arg1) {
  return window['go']['main']['App']['StopIntruderAttack'](arg1);
}

export function StopLocalService() {
  return window['go']['main']['App']['StopLocalService']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateAppConfig(arg1) {
  return window['go']['main']['App']['UpdateAppConfig'](arg1);
}

export function UpdateVulnerabilityStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateVulnerabilityStatus'](arg1, arg2);
}
